[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================
[[plugins]]
repo = 'tomasr/molokai'

# ==========================================================
# basic
# ==========================================================

# [[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcomenter.rc.vim
'''

[[plugins]]
# Show search result nicely
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins/anzu.rc.vim
'''

[[plugins]]
# Parensis completion
repo = 'LeafCage/yankround.vim.git'
hook_add = '''
source ~/.config/nvim/plugins/yankround.rc.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
# Edit binary
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
# Enhance f/F command in normal mode
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'milkypostman/vim-togglelist'
hook_add = '''
nmap <script> <silent> <C-l> :call ToggleLocationList()<CR>
nmap <script> <silent> <C-q> :call ToggleQuickfixList()<CR> " Bug: not work in neovim
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = ['vim-operator-user', 'vim-textobj-function', 'vim-textobj-user']
hook_add = '''
nmap <Space>/ <Plug>(operator-search)if
'''

[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'bitc/vim-bad-whitespace'

# ==========================================================
# linter
# ==========================================================

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neomake.rc.vim
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

# ==========================================================
# powerline
# ==========================================================

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'gcmt/taboo.vim'
depends = 'vim-airline'
hook_add = '''
"set guioptions-=e
"set sessionoptions+=tabpages,globals
let g:taboo_tab_format=' t%N %f%m '
let g:taboo_tabline = 0
'''

# ==========================================================
# terminal
# ==========================================================

[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neoterm.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimshell'
if = "!has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/vimshell.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('nvim')"
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# ==========================================================
# git
# ==========================================================

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_override_sign_column_highlight = 1
highlight clear SignColumn
"highlight SignColumn ctermbg=None
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

# ==========================================================
# others
# ==========================================================

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term = 237
let g:indentLine_color_gui = '#3c444d'
let g:indentLine_char = '¦'
'''

[[plugins]]
repo = 'fuenor/qfixgrep'
